const db = require("../database/connection");

exports.findAll = () => {
  return new Promise((resolve, reject) => {
    db.query("SELECT * FROM referencia_hematologia", (err, result) => {
      err ? reject(err) : resolve(result);
    });
  });
};

exports.create = (data) => {
  return new Promise((resolve, reject) => {
    const query = `
      INSERT INTO referencia_hematologia (
        id,
        chemacia_m, chemacia_f, chemacia_unidade,
        chemoglobina_m, chemoglobina_f, chemoglobina_unidade,
        chematocrito_m, chematocrito_f, chematocrito_unidade,
        cvcm_m, cvcm_f, cvcm_unidade,
        chcm_m, chcm_f, chcm_unidade,
        cchcw_m, cchcw_f, cchcw_unidade,
        crdw_m, crdw_f, crdw_unidade,
        cleucocitos_relativo, cleucocitos_relativo_unidade,
        cleucocitos_absoluto, cleucocitos_absoluto_unidade,
        cneutrofilos_relativo, cneutrofilos_relativo_unidade,
        cneutrofilos_absoluto, cneutrofilos_absoluto_unidade,
        cblastos_relativo, cblastos_relativo_unidade,
        cblastos_absoluto, cblastos_absoluto_unidade,
        cpromielocitos_relativo, cpromielocitos_relativo_unidade,
        cpromielocitos_absoluto, cpromielocitos_absoluto_unidade,
        cmielocitos_relativo, cmielocitos_relativo_unidade,
        cmielocitos_absoluto, cmielocitos_absoluto_unidade,
        cmetamielocitos_relativo, cmetamielocitos_relativo_unidade,
        cmetamielocitos_absoluto, cmetamielocitos_absoluto_unidade,
        cbastonetes_relativo, cbastonetes_relativo_unidade,
        cbastonetes_absoluto, cbastonetes_absoluto_unidade,
        csegmentados_relativo, csegmentados_relativo_unidade,
        csegmentados_absoluto, csegmentados_absoluto_unidade,
        ceosinofilos_relativo, ceosinofilos_relativo_unidade,
        ceosinofilos_absoluto, ceosinofilos_absoluto_unidade,
        cbasofilos_relativo, cbasofilos_relativo_unidade,
        cbasofilos_absoluto, cbasofilos_absoluto_unidade,
        clinfocitos_relativo, clinfocitos_relativo_unidade,
        clinfocitos_absoluto, clinfocitos_absoluto_unidade,
        clinfocitos_atipicos_relativo, clinfocitos_atipicos_relativo_unidade,
        clinfocitos_atipicos_absoluto, clinfocitos_atipicos_absoluto_unidade,
        cmonocitos_relativo, cmonocitos_relativo_unidade,
        cmonocitos_absoluto, cmonocitos_absoluto_unidade,
        cmieloblastos_relativo, cmieloblastos_relativo_unidade,
        cmieloblastos_absoluto, cmieloblastos_absoluto_unidade,
        coutras_celulas_relativo, coutras_celulas_relativo_unidade,
        coutras_celulas_absoluto, coutras_celulas_absoluto_unidade,
        ccelulas_linfoides_relativo, ccelulas_linfoides_relativo_unidade,
        ccelulas_linfoides_absoluto, ccelulas_linfoides_absoluto_unidade,
        ccelulas_monocitoides_relativo, ccelulas_monocitoides_relativo_unidade,
        ccelulas_monocitoides_absoluto, ccelulas_monocitoides_absoluto_unidade,
        cplaquetas, cplaquetas_unidade,
        cvolume_plaquetario_medio, cvolume_plaquetario_medio_unidade
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;

    const values = [
      data.id,
      data.chemacia_m,
      data.chemacia_f,
      data.chemacia_unidade,
      data.chemoglobina_m,
      data.chemoglobina_f,
      data.chemoglobina_unidade,
      data.chematocrito_m,
      data.chematocrito_f,
      data.chematocrito_unidade,
      data.cvcm_m,
      data.cvcm_f,
      data.cvcm_unidade,
      data.chcm_m,
      data.chcm_f,
      data.chcm_unidade,
      data.cchcw_m,
      data.cchcw_f,
      data.cchcw_unidade,
      data.crdw_m,
      data.crdw_f,
      data.crdw_unidade,
      data.cleucocitos_relativo,
      data.cleucocitos_relativo_unidade,
      data.cleucocitos_absoluto,
      data.cleucocitos_absoluto_unidade,
      data.cneutrofilos_relativo,
      data.cneutrofilos_relativo_unidade,
      data.cneutrofilos_absoluto,
      data.cneutrofilos_absoluto_unidade,
      data.cblastos_relativo,
      data.cblastos_relativo_unidade,
      data.cblastos_absoluto,
      data.cblastos_absoluto_unidade,
      data.cpromielocitos_relativo,
      data.cpromielocitos_relativo_unidade,
      data.cpromielocitos_absoluto,
      data.cpromielocitos_absoluto_unidade,
      data.cmielocitos_relativo,
      data.cmielocitos_relativo_unidade,
      data.cmielocitos_absoluto,
      data.cmielocitos_absoluto_unidade,
      data.cmetamielocitos_relativo,
      data.cmetamielocitos_relativo_unidade,
      data.cmetamielocitos_absoluto,
      data.cmetamielocitos_absoluto_unidade,
      data.cbastonetes_relativo,
      data.cbastonetes_relativo_unidade,
      data.cbastonetes_absoluto,
      data.cbastonetes_absoluto_unidade,
      data.csegmentados_relativo,
      data.csegmentados_relativo_unidade,
      data.csegmentados_absoluto,
      data.csegmentados_absoluto_unidade,
      data.ceosinofilos_relativo,
      data.ceosinofilos_relativo_unidade,
      data.ceosinofilos_absoluto,
      data.ceosinofilos_absoluto_unidade,
      data.cbasofilos_relativo,
      data.cbasofilos_relativo_unidade,
      data.cbasofilos_absoluto,
      data.cbasofilos_absoluto_unidade,
      data.clinfocitos_relativo,
      data.clinfocitos_relativo_unidade,
      data.clinfocitos_absoluto,
      data.clinfocitos_absoluto_unidade,
      data.clinfocitos_atipicos_relativo,
      data.clinfocitos_atipicos_relativo_unidade,
      data.clinfocitos_atipicos_absoluto,
      data.clinfocitos_atipicos_absoluto_unidade,
      data.cmonocitos_relativo,
      data.cmonocitos_relativo_unidade,
      data.cmonocitos_absoluto,
      data.cmonocitos_absoluto_unidade,
      data.cmieloblastos_relativo,
      data.cmieloblastos_relativo_unidade,
      data.cmieloblastos_absoluto,
      data.cmieloblastos_absoluto_unidade,
      data.coutras_celulas_relativo,
      data.coutras_celulas_relativo_unidade,
      data.coutras_celulas_absoluto,
      data.coutras_celulas_absoluto_unidade,
      data.ccelulas_linfoides_relativo,
      data.ccelulas_linfoides_relativo_unidade,
      data.ccelulas_linfoides_absoluto,
      data.ccelulas_linfoides_absoluto_unidade,
      data.ccelulas_monocitoides_relativo,
      data.ccelulas_monocitoides_relativo_unidade,
      data.ccelulas_monocitoides_absoluto,
      data.ccelulas_monocitoides_absoluto_unidade,
      data.cplaquetas,
      data.cplaquetas_unidade,
      data.cvolume_plaquetario_medio,
      data.cvolume_plaquetario_medio_unidade,
    ];

    console.log("Total de colunas na query:", 94);
    console.log("Total de placeholders:", (query.match(/\?/g) || []).length);
    console.log("Total de valores no array:", values.length);

    db.query(query, values, (err, result) => {
      if (err) {
        console.error("Erro ao executar query:", err);
        reject(err);
      } else {
        resolve(result);
      }
    });
  });
};

exports.update = (id, data) => {
  return new Promise((resolve, reject) => {
    const query = `
      UPDATE referencia_hematologia SET
        chemacia_m = ?, chemacia_f = ?, chemacia_unidade = ?,
        chemoglobina_m = ?, chemoglobina_f = ?, chemoglobina_unidade = ?,
        chematocrito_m = ?, chematocrito_f = ?, chematocrito_unidade = ?,
        cvcm_m = ?, cvcm_f = ?, cvcm_unidade = ?,
        chcm_m = ?, chcm_f = ?, chcm_unidade = ?,
        cchcw_m = ?, cchcw_f = ?, cchcw_unidade = ?,
        crdw_m = ?, crdw_f = ?, crdw_unidade = ?,
        cleucocitos_relativo = ?, cleucocitos_relativo_unidade = ?,
        cleucocitos_absoluto = ?, cleucocitos_absoluto_unidade = ?,
        cneutrofilos_relativo = ?, cneutrofilos_relativo_unidade = ?,
        cneutrofilos_absoluto = ?, cneutrofilos_absoluto_unidade = ?,
        cblastos_relativo = ?, cblastos_relativo_unidade = ?,
        cblastos_absoluto = ?, cblastos_absoluto_unidade = ?,
        cpromielocitos_relativo = ?, cpromielocitos_relativo_unidade = ?,
        cpromielocitos_absoluto = ?, cpromielocitos_absoluto_unidade = ?,
        cmielocitos_relativo = ?, cmielocitos_relativo_unidade = ?,
        cmielocitos_absoluto = ?, cmielocitos_absoluto_unidade = ?,
        cmetamielocitos_relativo = ?, cmetamielocitos_relativo_unidade = ?,
        cmetamielocitos_absoluto = ?, cmetamielocitos_absoluto_unidade = ?,
        cbastonetes_relativo = ?, cbastonetes_relativo_unidade = ?,
        cbastonetes_absoluto = ?, cbastonetes_absoluto_unidade = ?,
        csegmentados_relativo = ?, csegmentados_relativo_unidade = ?,
        csegmentados_absoluto = ?, csegmentados_absoluto_unidade = ?,
        ceosinofilos_relativo = ?, ceosinofilos_relativo_unidade = ?,
        ceosinofilos_absoluto = ?, ceosinofilos_absoluto_unidade = ?,
        cbasofilos_relativo = ?, cbasofilos_relativo_unidade = ?,
        cbasofilos_absoluto = ?, cbasofilos_absoluto_unidade = ?,
        clinfocitos_relativo = ?, clinfocitos_relativo_unidade = ?,
        clinfocitos_absoluto = ?, clinfocitos_absoluto_unidade = ?,
        clinfocitos_atipicos_relativo = ?, clinfocitos_atipicos_relativo_unidade = ?,
        clinfocitos_atipicos_absoluto = ?, clinfocitos_atipicos_absoluto_unidade = ?,
        cmonocitos_relativo = ?, cmonocitos_relativo_unidade = ?,
        cmonocitos_absoluto = ?, cmonocitos_absoluto_unidade = ?,
        cmieloblastos_relativo = ?, cmieloblastos_relativo_unidade = ?,
        cmieloblastos_absoluto = ?, cmieloblastos_absoluto_unidade = ?,
        coutras_celulas_relativo = ?, coutras_celulas_relativo_unidade = ?,
        coutras_celulas_absoluto = ?, coutras_celulas_absoluto_unidade = ?,
        ccelulas_linfoides_relativo = ?, ccelulas_linfoides_relativo_unidade = ?,
        ccelulas_linfoides_absoluto = ?, ccelulas_linfoides_absoluto_unidade = ?,
        ccelulas_monocitoides_relativo = ?, ccelulas_monocitoides_relativo_unidade = ?,
        ccelulas_monocitoides_absoluto = ?, ccelulas_monocitoides_absoluto_unidade = ?,
        cplaquetas = ?, cplaquetas_unidade = ?,
        cvolume_plaquetario_medio = ?, cvolume_plaquetario_medio_unidade = ?
      WHERE id = ?
    `;

    const values = [
      data.chemacia_m,
      data.chemacia_f,
      data.chemacia_unidade,
      data.chemoglobina_m,
      data.chemoglobina_f,
      data.chemoglobina_unidade,
      data.chematocrito_m,
      data.chematocrito_f,
      data.chematocrito_unidade,
      data.cvcm_m,
      data.cvcm_f,
      data.cvcm_unidade,
      data.chcm_m,
      data.chcm_f,
      data.chcm_unidade,
      data.cchcw_m,
      data.cchcw_f,
      data.cchcw_unidade,
      data.crdw_m,
      data.crdw_f,
      data.crdw_unidade,
      data.cleucocitos_relativo,
      data.cleucocitos_relativo_unidade,
      data.cleucocitos_absoluto,
      data.cleucocitos_absoluto_unidade,
      data.cneutrofilos_relativo,
      data.cneutrofilos_relativo_unidade,
      data.cneutrofilos_absoluto,
      data.cneutrofilos_absoluto_unidade,
      data.cblastos_relativo,
      data.cblastos_relativo_unidade,
      data.cblastos_absoluto,
      data.cblastos_absoluto_unidade,
      data.cpromielocitos_relativo,
      data.cpromielocitos_relativo_unidade,
      data.cpromielocitos_absoluto,
      data.cpromielocitos_absoluto_unidade,
      data.cmielocitos_relativo,
      data.cmielocitos_relativo_unidade,
      data.cmielocitos_absoluto,
      data.cmielocitos_absoluto_unidade,
      data.cmetamielocitos_relativo,
      data.cmetamielocitos_relativo_unidade,
      data.cmetamielocitos_absoluto,
      data.cmetamielocitos_absoluto_unidade,
      data.cbastonetes_relativo,
      data.cbastonetes_relativo_unidade,
      data.cbastonetes_absoluto,
      data.cbastonetes_absoluto_unidade,
      data.csegmentados_relativo,
      data.csegmentados_relativo_unidade,
      data.csegmentados_absoluto,
      data.csegmentados_absoluto_unidade,
      data.ceosinofilos_relativo,
      data.ceosinofilos_relativo_unidade,
      data.ceosinofilos_absoluto,
      data.ceosinofilos_absoluto_unidade,
      data.cbasofilos_relativo,
      data.cbasofilos_relativo_unidade,
      data.cbasofilos_absoluto,
      data.cbasofilos_absoluto_unidade,
      data.clinfocitos_relativo,
      data.clinfocitos_relativo_unidade,
      data.clinfocitos_absoluto,
      data.clinfocitos_absoluto_unidade,
      data.clinfocitos_atipicos_relativo,
      data.clinfocitos_atipicos_relativo_unidade,
      data.clinfocitos_atipicos_absoluto,
      data.clinfocitos_atipicos_absoluto_unidade,
      data.cmonocitos_relativo,
      data.cmonocitos_relativo_unidade,
      data.cmonocitos_absoluto,
      data.cmonocitos_absoluto_unidade,
      data.cmieloblastos_relativo,
      data.cmieloblastos_relativo_unidade,
      data.cmieloblastos_absoluto,
      data.cmieloblastos_absoluto_unidade,
      data.coutras_celulas_relativo,
      data.coutras_celulas_relativo_unidade,
      data.coutras_celulas_absoluto,
      data.coutras_celulas_absoluto_unidade,
      data.ccelulas_linfoides_relativo,
      data.ccelulas_linfoides_relativo_unidade,
      data.ccelulas_linfoides_absoluto,
      data.ccelulas_linfoides_absoluto_unidade,
      data.ccelulas_monocitoides_relativo,
      data.ccelulas_monocitoides_relativo_unidade,
      data.ccelulas_monocitoides_absoluto,
      data.ccelulas_monocitoides_absoluto_unidade,
      data.cplaquetas,
      data.cplaquetas_unidade,
      data.cvolume_plaquetario_medio,
      data.cvolume_plaquetario_medio_unidade,
      id,
    ];

    db.query(query, values, (err, result) => {
      if (err) {
        console.error("Erro ao executar query de update:", err);
        reject(err);
      } else {
        resolve(result);
      }
    });
  });
};
