const db = require("../database/connection");

exports.findAll = () => {
  return new Promise((resolve, reject) => {
    db.query("SELECT * FROM referencia_hematologia", (err, result) => {
      err ? reject(err) : resolve(result);
    });
  });
};

exports.create = (data) => {
  return new Promise((resolve, reject) => {
    const query = `
    INSERT INTO referencia_hematologia (
      id,
      chemacia_m, chemacia_f, chemacia_unidade,
      chemoglobina_m, chemoglobina_f, chemoglobina_unidade,
      chematocrito_m, chematocrito_f, chematocrito_unidade,
      cvcm_m, cvcm_f, cvcm_unidade,
      chcm_m, chcm_f, chcm_unidade,
      cchcw_m, cchcw_f, cchcw_unidade,
      crdw_m, crdw_f, crdw_unidade,
      cleucocitos_relativo, cleucocitos_relativo_unidade,
      cleucocitos_absoluto, cleucocitos_absoluto_unidade,
      cneutrofilos_relativo, cneutrofilos_relativo_unidade,
      cneutrofilos_absoluto, cneutrofilos_absoluto_unidade,
      cblastos_relativo, cblastos_relativo_unidade,
      cblastos_absoluto, cblastos_absoluto_unidade,
      cpromielocitos_relativo, cpromielocitos_relativo_unidade,
      cpromielocitos_absoluto, cpromielocitos_absoluto_unidade,
      cmielocitos_relativo, cmielocitos_relativo_unidade,
      cmielocitos_absoluto, cmielocitos_absoluto_unidade,
      cmetamielocitos_relativo, cmetamielocitos_relativo_unidade,
      cmetamielocitos_absoluto, cmetamielocitos_absoluto_unidade,
      cbastonetes_relativo, cbastonetes_relativo_unidade,
      cbastonetes_absoluto, cbastonetes_absoluto_unidade,
      csegmentados_relativo, csegmentados_relativo_unidade,
      csegmentados_absoluto, csegmentados_absoluto_unidade,
      ceosinofilos_relativo, ceosinofilos_relativo_unidade,
      ceosinofilos_absoluto, ceosinofilos_absoluto_unidade,
      cbasofilos_relativo, cbasofilos_relativo_unidade,
      cbasofilos_absoluto, cbasofilos_absoluto_unidade,
      clinfocitos_relativo, clinfocitos_relativo_unidade,
      clinfocitos_absoluto, clinfocitos_absoluto_unidade,
      clinfocitos_atipicos_relativo, clinfocitos_atipicos_relativo_unidade,
      clinfocitos_atipicos_absoluto, clinfocitos_atipicos_absoluto_unidade,
      cmonocitos_relativo, cmonocitos_relativo_unidade,
      cmonocitos_absoluto, cmonocitos_absoluto_unidade,
      cmieloblastos_relativo, cmieloblastos_relativo_unidade,
      cmieloblastos_absoluto, cmieloblastos_absoluto_unidade,
      coutras_celulas_relativo, coutras_celulas_relativo_unidade,
      coutras_celulas_absoluto, coutras_celulas_absoluto_unidade,
      ccelulas_linfoides_relativo, ccelulas_linfoides_relativo_unidade,
      ccelulas_linfoides_absoluto, ccelulas_linfoides_absoluto_unidade,
      ccelulas_monocitoides_relativo, ccelulas_monocitoides_relativo_unidade,
      ccelulas_monocitoides_absoluto, ccelulas_monocitoides_absoluto_unidade,
      cplaquetas, cplaquetas_unidade,
      cvolume_plaquetario_medio, cvolume_plaquetario_medio_unidade
    ) VALUES (
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    )
  `;

    const values = [
      data.id,
      data.hemacia_m,
      data.hemacia_f,
      data.hemacia_unidade,
      data.hemoglobina_m,
      data.hemoglobina_f,
      data.hemoglobina_unidade,
      data.hematocrito_m,
      data.hematocrito_f,
      data.hematocrito_unidade,
      data.cvcm_m,
      data.cvcm_f,
      data.cvcm_unidade,
      data.chcm_m,
      data.chcm_f,
      data.chcm_unidade,
      data.cchcw_m,
      data.cchcw_f,
      data.cchcw_unidade,
      data.crdw_m,
      data.crdw_f,
      data.crdw_unidade,
      data.leucocitos_relativo,
      data.leucocitos_relativo_unidade,
      data.leucocitos_absoluto,
      data.leucocitos_absoluto_unidade,
      data.neutrofilos_relativo,
      data.neutrofilos_relativo_unidade,
      data.neutrofilos_absoluto,
      data.neutrofilos_absoluto_unidade,
      data.blastos_relativo,
      data.blastos_relativo_unidade,
      data.blastos_absoluto,
      data.blastos_absoluto_unidade,
      data.promielocitos_relativo,
      data.promielocitos_relativo_unidade,
      data.promielocitos_absoluto,
      data.promielocitos_absoluto_unidade,
      data.mielocitos_relativo,
      data.mielocitos_relativo_unidade,
      data.mielocitos_absoluto,
      data.mielocitos_absoluto_unidade,
      data.metamielocitos_relativo,
      data.metamielocitos_relativo_unidade,
      data.metamielocitos_absoluto,
      data.metamielocitos_absoluto_unidade,
      data.bastonetes_relativo,
      data.bastonetes_relativo_unidade,
      data.bastonetes_absoluto,
      data.bastonetes_absoluto_unidade,
      data.segmentados_relativo,
      data.segmentados_relativo_unidade,
      data.segmentados_absoluto,
      data.segmentados_absoluto_unidade,
      data.eosinofilos_relativo,
      data.eosinofilos_relativo_unidade,
      data.eosinofilos_absoluto,
      data.eosinofilos_absoluto_unidade,
      data.basofilos_relativo,
      data.basofilos_relativo_unidade,
      data.basofilos_absoluto,
      data.basofilos_absoluto_unidade,
      data.linfocitos_relativo,
      data.linfocitos_relativo_unidade,
      data.linfocitos_absoluto,
      data.linfocitos_absoluto_unidade,
      data.linfocitos_atipicos_relativo,
      data.linfocitos_atipicos_relativo_unidade,
      data.linfocitos_atipicos_absoluto,
      data.linfocitos_atipicos_absoluto_unidade,
      data.monocitos_relativo,
      data.monocitos_relativo_unidade,
      data.monocitos_absoluto,
      data.monocitos_absoluto_unidade,
      data.mieloblastos_relativo,
      data.mieloblastos_relativo_unidade,
      data.mieloblastos_absoluto,
      data.mieloblastos_absoluto_unidade,
      data.outras_celulas_relativo,
      data.outras_celulas_relativo_unidade,
      data.outras_celulas_absoluto,
      data.outras_celulas_absoluto_unidade,
      data.celulas_linfoides_relativo,
      data.celulas_linfoides_relativo_unidade,
      data.celulas_linfoides_absoluto,
      data.celulas_linfoides_absoluto_unidade,
      data.celulas_monocitoides_relativo,
      data.celulas_monocitoides_relativo_unidade,
      data.celulas_monocitoides_absoluto,
      data.celulas_monocitoides_absoluto_unidade,
      data.plaquetas,
      data.plaquetas_unidade,
      data.volume_plaquetario_medio,
      data.volume_plaquetario_medio_unidade,
    ];

    db.query(query, values, (err, result) => {
      err ? reject(err) : resolve(result);
    });
  });
};

exports.update = (id, data) => {
  return new Promise((resolve, reject) => {
    const query = `
      UPDATE referencia_hematologia SET
        chemacia_m = ?, chemacia_f = ?, chemacia_unidade = ?,
        chemoglobina_m = ?, chemoglobina_f = ?, chemoglobina_unidade = ?,
        chematocrito_m = ?, chematocrito_f = ?, chematocrito_unidade = ?,
        cvcm_m = ?, cvcm_f = ?, cvcm_unidade = ?,
        chcm_m = ?, chcm_f = ?, chcm_unidade = ?,
        cchcw_m = ?, cchcw_f = ?, cchcw_unidade = ?,
        crdw_m = ?, crdw_f = ?, crdw_unidade = ?,
        cleucocitos_relativo = ?, cleucocitos_relativo_unidade = ?,
        cleucocitos_absoluto = ?, cleucocitos_absoluto_unidade = ?,
        cneutrofilos_relativo = ?, cneutrofilos_relativo_unidade = ?,
        cneutrofilos_absoluto = ?, cneutrofilos_absoluto_unidade = ?,
        cblastos_relativo = ?, cblastos_relativo_unidade = ?,
        cblastos_absoluto = ?, cblastos_absoluto_unidade = ?,
        cpromielocitos_relativo = ?, cpromielocitos_relativo_unidade = ?,
        cpromielocitos_absoluto = ?, cpromielocitos_absoluto_unidade = ?,
        cmielocitos_relativo = ?, cmielocitos_relativo_unidade = ?,
        cmielocitos_absoluto = ?, cmielocitos_absoluto_unidade = ?,
        cmetamielocitos_relativo = ?, cmetamielocitos_relativo_unidade = ?,
        cmetamielocitos_absoluto = ?, cmetamielocitos_absoluto_unidade = ?,
        cbastonetes_relativo = ?, cbastonetes_relativo_unidade = ?,
        cbastonetes_absoluto = ?, cbastonetes_absoluto_unidade = ?,
        csegmentados_relativo = ?, csegmentados_relativo_unidade = ?,
        csegmentados_absoluto = ?, csegmentados_absoluto_unidade = ?,
        ceosinofilos_relativo = ?, ceosinofilos_relativo_unidade = ?,
        ceosinofilos_absoluto = ?, ceosinofilos_absoluto_unidade = ?,
        cbasofilos_relativo = ?, cbasofilos_relativo_unidade = ?,
        cbasofilos_absoluto = ?, cbasofilos_absoluto_unidade = ?,
        clinfocitos_relativo = ?, clinfocitos_relativo_unidade = ?,
        clinfocitos_absoluto = ?, clinfocitos_absoluto_unidade = ?,
        clinfocitos_atipicos_relativo = ?, clinfocitos_atipicos_relativo_unidade = ?,
        clinfocitos_atipicos_absoluto = ?, clinfocitos_atipicos_absoluto_unidade = ?,
        cmonocitos_relativo = ?, cmonocitos_relativo_unidade = ?,
        cmonocitos_absoluto = ?, cmonocitos_absoluto_unidade = ?,
        cmieloblastos_relativo = ?, cmieloblastos_relativo_unidade = ?,
        cmieloblastos_absoluto = ?, cmieloblastos_absoluto_unidade = ?,
        coutras_celulas_relativo = ?, coutras_celulas_relativo_unidade = ?,
        coutras_celulas_absoluto = ?, coutras_celulas_absoluto_unidade = ?,
        ccelulas_linfoides_relativo = ?, ccelulas_linfoides_relativo_unidade = ?,
        ccelulas_linfoides_absoluto = ?, ccelulas_linfoides_absoluto_unidade = ?,
        ccelulas_monocitoides_relativo = ?, ccelulas_monocitoides_relativo_unidade = ?,
        ccelulas_monocitoides_absoluto = ?, ccelulas_monocitoides_absoluto_unidade = ?,
        cplaquetas = ?, cplaquetas_unidade = ?,
        cvolume_plaquetario_medio = ?, cvolume_plaquetario_medio_unidade = ?
      WHERE id = ?
    `;

    const values = [
      data.hemacia_m,
      data.hemacia_f,
      data.hemacia_unidade,
      data.hemoglobina_m,
      data.hemoglobina_f,
      data.hemoglobina_unidade,
      data.hematocrito_m,
      data.hematocrito_f,
      data.hematocrito_unidade,
      data.cvcm_m,
      data.cvcm_f,
      data.cvcm_unidade,
      data.chcm_m,
      data.chcm_f,
      data.chcm_unidade,
      data.cchcw_m,
      data.cchcw_f,
      data.cchcw_unidade,
      data.crdw_m,
      data.crdw_f,
      data.crdw_unidade,
      data.leucocitos_relativo,
      data.leucocitos_relativo_unidade,
      data.leucocitos_absoluto,
      data.leucocitos_absoluto_unidade,
      data.neutrofilos_relativo,
      data.neutrofilos_relativo_unidade,
      data.neutrofilos_absoluto,
      data.neutrofilos_absoluto_unidade,
      data.blastos_relativo,
      data.blastos_relativo_unidade,
      data.blastos_absoluto,
      data.blastos_absoluto_unidade,
      data.promielocitos_relativo,
      data.promielocitos_relativo_unidade,
      data.promielocitos_absoluto,
      data.promielocitos_absoluto_unidade,
      data.mielocitos_relativo,
      data.mielocitos_relativo_unidade,
      data.mielocitos_absoluto,
      data.mielocitos_absoluto_unidade,
      data.metamielocitos_relativo,
      data.metamielocitos_relativo_unidade,
      data.metamielocitos_absoluto,
      data.metamielocitos_absoluto_unidade,
      data.bastonetes_relativo,
      data.bastonetes_relativo_unidade,
      data.bastonetes_absoluto,
      data.bastonetes_absoluto_unidade,
      data.segmentados_relativo,
      data.segmentados_relativo_unidade,
      data.segmentados_absoluto,
      data.segmentados_absoluto_unidade,
      data.eosinofilos_relativo,
      data.eosinofilos_relativo_unidade,
      data.eosinofilos_absoluto,
      data.eosinofilos_absoluto_unidade,
      data.basofilos_relativo,
      data.basofilos_relativo_unidade,
      data.basofilos_absoluto,
      data.basofilos_absoluto_unidade,
      data.linfocitos_relativo,
      data.linfocitos_relativo_unidade,
      data.linfocitos_absoluto,
      data.linfocitos_absoluto_unidade,
      data.linfocitos_atipicos_relativo,
      data.linfocitos_atipicos_relativo_unidade,
      data.linfocitos_atipicos_absoluto,
      data.linfocitos_atipicos_absoluto_unidade,
      data.monocitos_relativo,
      data.monocitos_relativo_unidade,
      data.monocitos_absoluto,
      data.monocitos_absoluto_unidade,
      data.mieloblastos_relativo,
      data.mieloblastos_relativo_unidade,
      data.mieloblastos_absoluto,
      data.mieloblastos_absoluto_unidade,
      data.outras_celulas_relativo,
      data.outras_celulas_relativo_unidade,
      data.outras_celulas_absoluto,
      data.outras_celulas_absoluto_unidade,
      data.celulas_linfoides_relativo,
      data.celulas_linfoides_relativo_unidade,
      data.celulas_linfoides_absoluto,
      data.celulas_linfoides_absoluto_unidade,
      data.celulas_monocitoides_relativo,
      data.celulas_monocitoides_relativo_unidade,
      data.celulas_monocitoides_absoluto,
      data.celulas_monocitoides_absoluto_unidade,
      data.plaquetas,
      data.plaquetas_unidade,
      data.volume_plaquetario_medio,
      data.volume_plaquetario_medio_unidade,
      id,
    ];

    db.query(query, values, (err, result) => {
      if (err) reject(err);
      else resolve(result);
    });
  });
};
